### ISSUE TITLE
run_and_plot.sh failing with package dependency error

### ISSUE THREAD

**Issue by notmgsk** [ArlineQ/arline_benchmarks#1]
```
# python --version
Python 3.6.9
```

```
# sh run_and_plot.sh 
Traceback (most recent call last):
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.8.0 (/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages), Requirement.parse('protobuf>=3.12.0'), {'google-api-core'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mgsk/hackery/arline_benchmarks/venv/bin/arline-benchmarks-runner", line 4, in <module>
    __import__('pkg_resources').require('arline-benchmarks==0.1.8')
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    @_call_aside
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3244, in _call_aside
    f(*args, **kwargs)
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3273, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.8.0 (/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages), Requirement.parse('protobuf>=3.12.0'), {'google-api-core'})
Traceback (most recent call last):
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.8.0 (/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages), Requirement.parse('protobuf>=3.12.0'), {'google-api-core'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mgsk/hackery/arline_benchmarks/venv/bin/arline-latex-report-generator", line 4, in <module>
    __import__('pkg_resources').require('arline-benchmarks==0.1.8')
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    @_call_aside
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3244, in _call_aside
    f(*args, **kwargs)
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3273, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.8.0 (/home/mgsk/hackery/arline_benchmarks/venv/lib/python3.6/site-packages), Requirement.parse('protobuf>=3.12.0'), {'google-api-core'})
```

**Comment by SurrealMind** [comment]
Hi notmgsk!

Thank you for your feedback. This issue is related to the Cirq [issue](https://github.com/quantumlib/Cirq/issues/3110). 
The reason is that Cirq did not fix the version of `google-api-core`, but the new `google-api-core` release is not compatible with Cirq 0.6.0. It can be fixed by setting a certain version of `google-api-core`.

This command should fix your problem:
`pip install google-api-core==1.20.0`

**Comment by notmgsk** [comment]
Awesome, I'll give it a try later and then close this.
